### ISSUE TITLE
NuGet package

### ISSUE THREAD

**Issue by wonea** [rvhuang/kmp-algorithm#2]
A NuGet package would be very helpful.

**Comment by rvhuang** [comment]
Will do in near future. Before that I will add documentary comments first.

**Comment by rvhuang** [comment]
Package is now available at MyGet. 

    PM> Install-Package AlgorithmForce.Searching -Source https://www.myget.org/F/algorithm-force/api/v3/index.json

**Comment by wonea** [comment]
Is there enough documentation to warrant a full NuGet release? I'm having trouble pulling from MyGet. Manual download works, but not through a feed.

**Comment by rvhuang** [comment]
@wonea will release on NuGet too. Thanks for reminding.
